[build]
  command = "npm run build"
  publish = "dist/"

[[redirects]]
  from = "https://reallysketch.netlify.com/*"
  to = "https://reallysketch.com/:splat"
  force = true

[[redirects]]
  from = "/drawing.png"
  to = "/thumbnail.png"

[[redirects]]
  from = "/about.html"
  to = "/"

[[redirects]]
  from = "/terms.html"
  to = "/terms/"

[[redirects]]
  from = "/privacy.html"
  to = "/privacy/"
